kind: Pod 
apiVersion: v1
metadata:
  name: email
spec:
  volumes:
  - name: app-config
    configMap:
      name: example-configmap
  containers:
  - name: email
    image: IMAGE_REPO:VERSION
    volumeMounts:
    - name: app-config
      mountPath: /tmp
  restartPolicy: Never